name: ğŸ”¨ Compile

on:
  workflow_run:
    workflows: ["ğŸ·ï¸ Tag"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v4

      - name: ğŸ·ï¸ Determine Tag Name
        run: |
          git fetch --tags
          TAG_NAME=$(git describe --tags --abbrev=0)
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "Using tag: $TAG_NAME"

      - name: ğŸ Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: ğŸ“¦ Install dependencies
        run: task install

      - name: ğŸ“ Install LaTeX
        run: task install-tex

      - name: ğŸ§¼ Validate resume
        run: task validate

      - name: ğŸ“ Generate & Compile resume
        run: task generate compile -v OUTPUT_PDF=out/Horia_Delicoti_CV.pdf

      - name: ğŸ“¤ Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: Horia_Delicoti_CV.pdf
          path: out/Horia_Delicoti_CV.pdf
  
      - name: ğŸš€ Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: out/Horia_Delicoti_CV.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
