name: ğŸ”¨ Compile

on:
  workflow_run:
    workflows: ["ğŸ·ï¸ Tag"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v4

      - name: ğŸ Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: ğŸ“¦ Install dependencies
        run: make install

      - name: ğŸ“ Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full latexmk
    
      - name: ğŸ§¼ Validate resume
        run: make validate

      - name: ğŸ“ Generate & Compile resume
        run: make generate compile

      - name: ğŸ“¤ Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: out/Horia_Delicoti_CV.pdf
  
      - name: ğŸš€ Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: out/Horia_Delicoti_CV.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
